# Generated by Django 2.2.5 on 2020-04-26 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('line1', models.CharField(max_length=200)),
                ('line2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=2)),
                ('country', models.CharField(max_length=20)),
                ('postcode', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('lot_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('lot_name', models.CharField(max_length=200)),
                ('lot_hours', models.CharField(max_length=200)),
                ('lot_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('credit_card', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('expiration_month', models.CharField(max_length=2)),
                ('expiration_year', models.CharField(max_length=4)),
                ('cvv', models.CharField(max_length=3)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.Address')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('spot_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('spot_number', models.CharField(max_length=6)),
                ('spot_occupancy', models.CharField(max_length=1)),
                ('spot_availabiliy', models.CharField(max_length=200)),
                ('lot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.ParkingLot')),
                ('spot_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
