# Generated by Django 2.2.5 on 2020-04-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspot',
            name='booked_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
