# Generated by Django 2.2.5 on 2020-04-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_auto_20200427_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspot',
            name='booked_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='booked_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
