# Generated by Django 2.2.5 on 2020-04-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_auto_20200428_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspot',
            name='booked_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
