# Generated by Django 2.2.5 on 2020-04-28 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_auto_20200428_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingspot',
            old_name='booked_minutes',
            new_name='booked_minute',
        ),
    ]
