# Generated by Django 2.2.5 on 2020-04-28 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_auto_20200428_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspot',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
