# Generated by Django 2.2.5 on 2020-04-28 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0007_parkingspot_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspot',
            name='license_plate',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
